name: Deploy Jekyll site to Pages and Update Submodule

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Run every hour

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Updated to v2 for submodule support

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.146.0
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Add Linux platform to Gemfile.lock
        run: bundle lock --add-platform x86_64-linux

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Checkout repository with submodules
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Update submodule
        run: git submodule update --remote --recursive

      - name: Run Ruby command
        run: ruby convert.rb

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Run Pagefind
        run: npm_config_yes=true npx pagefind --site "rules_in_html"

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
